### ISSUE TITLE
add new account to existing list

### ISSUE THREAD

**Issue by crispinWeissfuss** [Rukenshia/saml2aws-auto#1]
#Hey ruke,
can you add a feature that I can add an aws account to an existing group.

Right now the only ways I found are
- extend the `.saml2aws-auto.yml`
- overwriting existing group (which would make it necessary to add every existing account to this new group again)

Thanks 
Crispin

**Comment by Rukenshia** [comment]
Will add an `--append` flag to the groups add command that will not delete existing accounts of that group
