### ISSUE TITLE
Error when using saml2aws-auto in cygwin

### ISSUE THREAD

**Issue by mtransier** [Rukenshia/saml2aws-auto#29]
**Describe the bug**
When calling saml2aws-auto in cygwin, the following error message appears:
`thread 'main' panicked at 'Cannot get console screen buffer info', /cargo/registry/src/github.com-1ecc6299db9ec823/crossterm-0.2.2/src/kernel/windows_kernel/kernel.rs:77:9`

**To Reproduce**
1. Go to cygwin bash shell
2. Run saml2aws-auto.exe
3. See error

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by Rukenshia** [comment]
@mtransier I've just pushed 1.6.1, should be available in a bit on the "Releases" page. Can you please retest? Does it work outside of cygwin, i.e. the normal windows command line?
