### ISSUE TITLE
Add "saml2aws-auto configure"

### ISSUE THREAD

**Issue by uhinze** [Rukenshia/saml2aws-auto#30]
**Is your feature request related to a problem? Please describe.**
When changing password with the IDP, I somehow need to change it in saml2aws-auto as well. You can manually go to the credential storage on your platform (in my case Windows Credential Manager), but it would be neat to have a command for that.

**Describe the solution you'd like**
"saml2aws-auto configure", kind of like the AWS CLI equivalent. By default (hitting enter), the previous values are used for IDP URL, user, and password. But you can change one or more of those values.

**Describe alternatives you've considered**
Document how to change passwords on major platforms.

**Comment by Rukenshia** [comment]
That command should already exist, did you try running saml2aws-auto configure on the latest version?

**Comment by uhinze** [comment]
Upgrading helps :-)
However, running configure will bring me back to the start now (localhost is default URL). Is there a use case for this? I’d say that usually you wanna keep the current values. 
What do you think about changing the behavior to keep the current values as default?

**Comment by Rukenshia** [comment]
@uhinze Will do!
