### ISSUE TITLE
Show AccountName during Login in Error case

### ISSUE THREAD

**Issue by crispinWeissfuss** [Rukenshia/saml2aws-auto#46]
**Feature Request Description**
When I run `saml-2-aws-auto login` I want to see the account names even if I have no access to it.
We use your tool in our company and have only temporary access to some prod accounts. 

**Solution Suggestion**
As you can see in the picture, the Account names are only shown when access was successful.
I would like to propose the account name even if I don't have access
`{{aws-account-name}} Principial not found.`
![image](https://user-images.githubusercontent.com/13432087/52631905-5b304780-2ec0-11e9-94ed-5d76a01a2daa.png)

This would it make more transparent to see which account is throwing the no-access error

Best
Crispin

**Comment by Rukenshia** [comment]
Fixed in #48
