### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by Rukenshia** [Rukenshia/saml2aws-auto#5]
Now that there's no hard dependency on `saml2aws` anymore, we can rename this tool.

**Comment by planchao** [comment]
hokey-pokey-tokey
ststvm (STS token vending machine)
redpill (matrix reference, 'i want in', active tokens could be named 'pills')
heimdallr (norse gate keeper)

**Comment by DJAlPee** [comment]
+1 on Heimdall, as he is the gate keeper of the Bifröst ;)
for CLI it could just be used `hdll`
