### ISSUE TITLE
Provide scoop installation

### ISSUE THREAD

**Issue by Rukenshia** [Rukenshia/saml2aws-auto#51]
Via: https://github.com/lukesampson/scoop/tree/master/bucket

**Comment by stevehipwell** [comment]
https://github.com/ScoopInstaller/Main/pull/435

**Comment by stevehipwell** [comment]
I've just created a *scoop* main bucket pull request for *saml2aws*, you could use this as a base.

https://github.com/ScoopInstaller/Main/pull/435
