### ISSUE TITLE
sam2aws-auto doesn't trigger token push

### ISSUE THREAD

**Issue by sammcj** [Rukenshia/saml2aws-auto#69]
**Describe the bug**

When configuring saml2aws-auto, the tool doesn't trigger the MFA approval push.

**To Reproduce**
Steps to reproduce the behaviour:

1. Use AzureAD as authentication provider.
2. Configure as below.
3. Don't get any push approval with MFA on Microsoft Authenticator app.

```
? IDP URL [localhost]: https://account.activedirectory.windowsazure.com
? IDP Username: <my.email@company.com>
? IDP Password:

All set!
If you need to reconfigure your details, use saml2aws-auto configure
? MFA Token [000000]:
Listing allowed roles for your account	FAIL

Could not add group:

	Could not find saml submit form
```

**Expected behaviour**

The same as aws-azure-login or saml2aws, where when you've entered your username and password you get a push to the Microsoft Authenticator app to approve/deny the login.

**Logs**

Please attach the complete log of the saml2aws-auto command you ran.

**Desktop (please complete the following information):**
 - OS: macOS 12.6
 - Version: 1.11.0

**Additional context**

Example saml2aws config:

```
[aws-account-1]
app_id               = <redacted big number>
url                  = https://account.activedirectory.windowsazure.com
username             = <my.email@company.com>
provider             = AzureAD
mfa                  = PhoneAppNotification
skip_verify          = false
timeout              = 0
aws_urn              = urn:amazon:webservices
aws_session_duration = 3600
aws_profile          = dosa-dev
resource_id          =
subdomain            =
role_arn             = arn:aws:iam::<redacted>:role/Developer
region               = ap-southeast-2
http_attempts_count  = 3
http_retry_delay     = 1
```

or the same example but using ~/.aws/config (saml2aws):

```
[profile aws-account-1]
azure_app_id_uri="https://signin.aws.amazon.com/saml#6"
azure_default_role_arn=arn:aws:iam::<redacted>:role/Developer
region=ap-southeast-2
sso_region=ap-southeast-2
azure_default_username=<my.email@company.com>
azure_default_duration_hours=1
azure_default_remember_me=true
azure_tenant_id=<redacted big number>
```

**Comment by Rukenshia** [comment]
Hi,

I'm afraid you won't be able to use `saml2aws-auto` in this case - only Keycloak/RH-SSO is supported as an identity provider.
