### ISSUE TITLE
Keeps Requesting MFA Token on Refresh

### ISSUE THREAD

**Issue by verehfy** [Rukenshia/saml2aws-auto#76]
**Describe the bug**
Since the changes to allow refreshing of multiple groups, when calling `saml2aws-auto refresh <group>` for a group that has a valid session, it keeps asking for an MFA token.

This causes annoyance when using s2a in scripts as you keep having to enter MFA tokens for valid sessions.

**Expected behavior**
If all groups have a valid session it just displays "Nothing to refresh. All accounts have valid sessions." and continues.

**Comment by Rukenshia** [comment]
> This causes annoyance when using s2a in scripts as you keep having to enter MFA tokens for valid sessions.

By that, do you mean that running `saml2aws-auto refresh <GROUPS>` asks for the MFA multiple times as well, or just once when running the refresh command (but not accounting for that all accounts in all groups could have valid sessions)?

**Comment by verehfy** [comment]
When wanting to refresh a specific group that has a valid token, i.e `saml2aws-auto refresh <tenancy>`, it will always ask for an MFA regardless of validity of the session.
